apiVersion: v1
kind: Service
metadata:
  name: payment-webhooks
  namespace: vibe-social
spec:
  selector:
    app: payment-webhooks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
